# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NTgwMTI4MDRlOWVjMjA3NmExNjI2MmJlOWQyMDlkMGJlODAzZTRmN2ZjNjQyYzdlNGEyZmEzMDBlOWRjNWExY2I4N2Q2NWIwMWNjYTYyOWFkNTZiNjYyM2IzNGNkZTJhYTlkMjU2ODEyYzA3MzBjMTUwZDliOTk1MjM3MDhjOGQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
